### ISSUE TITLE
TrailDBConstructor Seg Faults on `append()`

### ISSUE THREAD

**Issue by JoshVorick** [traildb/traildb#79] opened 2016-06-22 22:09 UTC
Sometimes when running `TrailDBConstructor.append()`, it seg faults. I believe it is a problem with the merge logic. When merging trails, it sometimes fudges the data when there are empty fields. Then, when you try and merge the database with fudged data, it causes a Segmentation Fault.

Here is some code that reproduces the bug on my machine about 50% of the time:
```python
#!/usr/bin/env python2.7
# coding: utf-8

from datetime import datetime, timedelta
from traildb import TrailDBConstructor, TrailDB
import uuid
from sys import path, argv

print "Creating 3 database constructors"
newTrailA = TrailDBConstructor("TEST_A", ["1", "2"])
newTrailB = TrailDBConstructor("TEST_B", ["1", "2"])

uid = uuid.uuid4().hex
t = datetime.now()
params = (
        "a",
        ''
    )
newTrailA.add(uid, t, params)
newTrailB.add(uid, t + timedelta(0,3), params)

print "Finalizing TEST_A and TEST_B"
newTrailA.finalize()
newTrailB.finalize()

for uuid, trail in TrailDB("TEST_A").trails():
    print uuid, list(trail)

for uuid, trail in TrailDB("TEST_B").trails():
    print uuid, list(trail)

print "Creating C"
newTrailC = TrailDBConstructor("TEST_C", ["1", "2"])

print newTrailC.append(TrailDB("TEST_A"))
print newTrailC.append(TrailDB("TEST_B"))

print "Finalizing C"
newTrailC.finalize()

for uuid, trail in TrailDB("TEST_C").trails():
    print uuid, list(trail)

print "Creating Z"
newTrailZ = TrailDBConstructor("TEST_Z", ["1", "2"])

# Cause a seg fault
print newTrailZ.append(TrailDB("TEST_C"))

print "FINALIZE Z"
newTrailZ.finalize()
```

**Comment by tuulos** [comment] 2016-06-23 06:09
Thanks @JoshVorick for a detailed issue. I will take a look.

**Comment by tuulos** [comment] 2016-06-26 22:20
the bug was caused by incorrect handling of empty fields in `tdb_cons_append`. It is now fixed and a test for it was added. Thanks @JoshVorick !

**Closed** 2016-06-26 22:32 UTC
